import type { Trail, TrailDifficulty, TrailShape } from "./types";

const nps = "https://www.nps.gov/";
const sources = {
  yosemite: nps + "yose/planyourvisit/valleyhikes.htm",
  mist: nps + "yose/planyourvisit/vernalnevadatrail.htm",
  lands: nps + "goga/planyourvisit/landsend.htm",
  tomales: nps + "thingstodo/hike-the-tomales-point-trail.htm",
  tam: "https://parks.ca.gov/?page_id=28465",
  joshua: nps + "jotr/planyourvisit/hiking.htm",
  skyline: nps + "mora/planyourvisit/skyline-trail.htm",
  nisqually: nps + "thingstodo/hike-nisqually-vista-trail.htm",
  moss: nps + "places/000/hall-of-mosses-trailhead.htm",
  hurricane: nps + "olym/planyourvisit/visiting-hurricane-ridge.htm",
  zion: nps + "zion/planyourvisit/zion-canyon-trail-descriptions.htm",
  bryce: nps + "brca/planyourvisit/day-hikes.htm",
  canyon: nps + "grca/planyourvisit/day-hiking.htm",
  rocky: nps + "romo/planyourvisit/list_hiking_trails.htm",
  glacier: nps + "glac/planyourvisit/hikingthetrails.htm",
  fairy: nps + "thingstodo/yell-trail-fairy-falls.htm",
  taggart: nps + "thingstodo/taggartlake.htm",
  jenny: nps + "grte/planyourvisit/jennylakeplan.htm",
  kilauea: nps + "havo/planyourvisit/hike_day_kilauea-iki.htm",
  devastation: nps + "havo/planyourvisit/hike_day_devastation.htm",
  diamond: "https://dlnr.hawaii.gov/dsp/parks/oahu/diamond-head-state-monument/",
};

type Seed = [slug: string, name: string, destination: string, region: string, distanceKm: number, elevationM: number | null, duration: string, difficulty: TrailDifficulty, shape: TrailShape, imageKey: string, tags: string[], why: string, route: string, guidance: string, bestTime: string, source: keyof typeof sources, trailhead: string];
// Distances are full described itineraries, rounded for discovery. Times are editorial
// estimates, not pace predictions. Null elevations have not been verified.
const seeds: Seed[] = [
  ["mist-trail", "Mist Trail to Vernal Fall", "Yosemite National Park", "California", 3.9, 300, "3 hr", "Strenuous", "Out & Back", "vernal", ["Waterfalls", "Granite", "Forest"], "A granite staircase beside a waterfall: Yosemite at its most immediate.", "From Happy Isles, climb past the footbridge to the top of Vernal Fall; return by the same route.", "Wet steps and exposed edges demand care. Check Mist Trail closures and detours before setting out.", "Spring–early summer for waterfall flow", "mist", "Happy Isles"],
  ["lower-yosemite-fall", "Lower Yosemite Fall", "Yosemite National Park", "California", 1.6, 15, "30–60 min", "Easy", "Loop", "yosemite-falls", ["Waterfalls", "Valley"], "A short walk with a very large soundtrack.", "Follow the signed loop from the Lower Yosemite Fall shuttle stop.", "Water is seasonal; stay off slippery rocks near the falls.", "Spring–early summer", "yosemite", "Lower Yosemite Fall shuttle stop"],
  ["upper-yosemite-falls", "Upper Yosemite Falls", "Yosemite National Park", "California", 11.6, 825, "6–8 hr", "Strenuous", "Out & Back", "upper-yosemite-falls", ["Waterfalls", "Granite", "Views"], "Earn a valley-wide perspective above Yosemite’s famous falls.", "Climb from Camp 4 to the top of Yosemite Falls and return.", "A sustained exposed climb. Carry water and avoid midday heat.", "Late spring–early summer, snow permitting", "yosemite", "Camp 4"],
  ["mirror-lake", "Mirror Lake", "Yosemite National Park", "California", 3.2, 30, "1 hr", "Easy", "Out & Back", "mirror-lake", ["Lake", "Forest", "Granite"], "Look up into Half Dome’s immense stone face.", "Walk from shuttle stop 17 to the lake and back; this is not the longer lake loop.", "The lake can dry out; do not cross Tenaya Creek to shortcut.", "Spring for reflections", "yosemite", "Mirror Lake shuttle stop"],
  ["bridalveil-fall", "Bridalveil Fall", "Yosemite National Park", "California", 0.8, 24, "20–30 min", "Easy", "Out & Back", "bridalveil", ["Waterfalls", "Valley"], "A brief introduction to the valley’s great vertical scale.", "Follow the paved path from the parking area to the viewing area and back.", "Spray makes paving slick. Remain in designated viewing areas.", "Spring for strong flow", "yosemite", "Bridalveil Fall parking area"],
  ["lands-end", "Lands End Coastal Trail", "San Francisco", "California", 5.5, null, "1.5–2 hr", "Moderate", "Out & Back", "lands", ["Coast", "City escape", "Views"], "Trade city streets for cypress, ocean air and glimpses of the Golden Gate.", "Follow the Coastal Trail from Lands End Lookout toward Eagle’s Point, then retrace your walk.", "Stairs and uneven sections interrupt the path. Keep away from unstable cliff edges.", "Spring–fall; bring a layer for fog", "lands", "Lands End Lookout"],
  ["tomales-point", "Tomales Point", "Point Reyes National Seashore", "California", 15.3, null, "4–6 hr", "Strenuous", "Out & Back", "tomales", ["Coast", "Wildlife", "Wildflowers"], "A long peninsula walk suspended between bay and Pacific.", "Start at Pierce Point Ranch and follow the ridge to Tomales Point; return the same way.", "The final section is sandy and unmaintained. Carry water, allow room for elk and avoid cliff edges.", "Spring wildflowers; fall coastal light", "tomales", "Pierce Point Ranch"],
  ["verna-dunshee", "Verna Dunshee Loop", "Mount Tamalpais State Park", "California", 1.2, null, "30–45 min", "Easy", "Loop", "verna-dunshee", ["Views", "City escape", "Coast"], "An unhurried circuit above the Bay Area.", "Circle East Peak on the paved Verna Dunshee Trail, returning to the same trailhead.", "Check road access before driving up; fog and wind can change the experience quickly.", "Spring–fall on clear days", "tam", "East Peak parking area"],
  ["hidden-valley", "Hidden Valley", "Joshua Tree National Park", "California", 1.6, 30, "1 hr", "Easy", "Loop", "joshua", ["Desert", "Boulders"], "A pocket-sized world of weathered rock and desert plants.", "Take the signed loop through the rock-enclosed valley.", "Bring water and sun protection; avoid extreme heat.", "October–April", "joshua", "Hidden Valley picnic area"],
  ["ryan-mountain", "Ryan Mountain", "Joshua Tree National Park", "California", 4.8, 320, "1.5–2.5 hr", "Strenuous", "Out & Back", "ryan-mountain", ["Desert", "Peaks", "Views"], "A broad desert panorama, earned one stone step at a time.", "Climb the established summit trail and descend the same way.", "Little shade and sustained climbing. Do not attempt in extreme heat.", "October–April", "joshua", "Ryan Mountain parking area"],
  ["barker-dam", "Barker Dam", "Joshua Tree National Park", "California", 1.8, 15, "1 hr", "Easy", "Loop", "barker-dam", ["Desert", "History", "Boulders"], "Discover the human history tucked between Joshua Tree’s boulders.", "Follow the loop from Barker Dam parking past the historic reservoir.", "The reservoir may be dry. Leave rock art and historic structures untouched.", "October–April", "joshua", "Barker Dam parking area"],
  ["skyline-trail", "Skyline Trail", "Mount Rainier National Park", "Pacific Northwest", 8.9, 518, "4–5 hr", "Strenuous", "Loop", "rainier", ["Alpine", "Wildflowers", "Glaciers"], "Walk into a vast alpine landscape beneath Mount Rainier.", "Follow the Skyline circuit from Paradise through Panorama Point and back toward Myrtle Falls.", "Snow can linger into summer. Follow signed seasonal routing; avoid traversing icy slopes.", "July–September, snow permitting", "skyline", "Paradise, Jackson Visitor Center"],
  ["nisqually-vista", "Nisqually Vista", "Mount Rainier National Park", "Pacific Northwest", 1.9, 61, "45–60 min", "Easy", "Loop", "nisqually-vista", ["Glaciers", "Alpine", "Wildflowers"], "Big mountain scenery on a smaller Paradise walk.", "Take the loop from the lower Paradise parking area to Nisqually Glacier viewpoints.", "Paving may be hidden by snow. Check Paradise road and trail access.", "July–September", "nisqually", "Lower Paradise parking area"],
  ["hall-of-mosses", "Hall of Mosses", "Olympic National Park", "Pacific Northwest", 1.3, null, "30–60 min", "Easy", "Loop", "moss", ["Forest", "Rainforest"], "Slow down beneath a canopy that seems to wear the forest itself.", "Follow the signed short loop from the Hoh Rain Forest visitor area.", "Roots, steps and short steep grades are present. Wear shoes with grip.", "Year-round; spring for vivid greens", "moss", "Hoh Rain Forest Visitor Center"],
  ["hurricane-hill", "Hurricane Hill", "Olympic National Park", "Pacific Northwest", 5.1, 213, "2–3 hr", "Moderate", "Out & Back", "olympic", ["Alpine", "Views", "Wildflowers"], "A high ridge walk with Olympic peaks spilling into the distance.", "Climb the Hurricane Hill trail from the road-end parking area and return.", "Check mountain road access. The ridge is exposed to wind and weather.", "July–September", "hurricane", "Hurricane Hill trailhead"],
  ["canyon-overlook", "Canyon Overlook", "Zion National Park", "Southwest", 1.6, 50, "1 hr", "Moderate", "Out & Back", "canyon-overlook", ["Desert", "Canyon", "Views"], "Zion opens out in a sweep of red rock and sky.", "Follow the rocky path east of the tunnel to the canyon viewpoint and back.", "Limited parking and exposed drops. Stay on the trail and away from edges.", "Spring–fall, avoiding midday heat", "zion", "East side of Zion–Mount Carmel Tunnel"],
  ["riverside-walk", "Riverside Walk", "Zion National Park", "Southwest", 3.5, 17, "1–1.5 hr", "Easy", "Out & Back", "riverside-walk", ["River", "Canyon", "Shade"], "Follow the Virgin River as the canyon walls draw closer.", "Take the paved path from Temple of Sinawava to its end and return. This itinerary does not enter the Narrows.", "Check shuttle access and trail alerts. River travel requires separate planning.", "Spring and fall", "zion", "Temple of Sinawava"],
  ["queens-garden-navajo", "Queen’s Garden / Navajo Loop", "Bryce Canyon National Park", "Southwest", 4.6, 191, "2–3 hr", "Moderate", "Loop", "bryce", ["Hoodoos", "Desert", "Geology"], "Step below the rim into Bryce’s sculpted stone city.", "Descend Queen’s Garden from Sunrise Point, ascend the Navajo Trail and reconnect along the rim.", "Check which Navajo branch is open. High elevation and the climb out add effort.", "May–October", "bryce", "Sunrise Point"],
  ["bryce-rim-walk", "Sunset to Sunrise Point", "Bryce Canyon National Park", "Southwest", 1.6, 12, "1 hr", "Easy", "Out & Back", "bryce-rim-walk", ["Views", "Hoodoos", "Geology"], "Stay above the amphitheater and let the hoodoos fill the horizon.", "Walk the paved rim section between Sunset and Sunrise points, then return.", "Paving can ice over; keep back from the rim and check the forecast.", "Spring–fall", "bryce", "Sunset Point"],
  ["ooh-aah-point", "South Kaibab to Ooh Aah Point", "Grand Canyon National Park", "Southwest", 2.9, null, "1–2 hr", "Strenuous", "Out & Back", "canyon", ["Canyon", "Desert", "Views"], "A short descent delivers an immense view into geological time.", "Descend South Kaibab Trail to Ooh Aah Point, then climb back to the rim.", "No water on this trail and little shade. The return is uphill; avoid extreme heat.", "Spring and fall", "canyon", "South Kaibab trailhead"],
  ["emerald-lake", "Emerald Lake", "Rocky Mountain National Park", "Rockies", 5.8, 185, "2–3 hr", "Moderate", "Out & Back", "emerald-lake", ["Alpine", "Lake", "Forest"], "A chain of mountain lakes leads to a dramatic rock-walled basin.", "Follow the trail from Bear Lake past Nymph and Dream lakes to Emerald Lake; retrace your steps.", "Check Bear Lake access reservations and shuttle details. Snow and afternoon storms are possible.", "June–September, snow permitting", "rocky", "Bear Lake trailhead"],
  ["alberta-falls", "Alberta Falls", "Rocky Mountain National Park", "Rockies", 2.6, 49, "1–1.5 hr", "Easy", "Out & Back", "alberta-falls", ["Waterfalls", "Forest"], "A tumbling mountain stream breaks through the forest.", "Walk from Glacier Gorge trailhead to Alberta Falls and back.", "Check Bear Lake corridor access. Stay back from slippery rocks beside the falls.", "June–September", "rocky", "Glacier Gorge trailhead"],
  ["avalanche-lake", "Avalanche Lake", "Glacier National Park", "Rockies", 7.4, 152, "2.5–4 hr", "Moderate", "Out & Back", "avalanche-lake", ["Lake", "Forest", "Waterfalls"], "Cedar forest gives way to a lake held in a huge mountain bowl.", "Start at Trail of the Cedars and follow the Avalanche Lake trail to the near lakeshore, then return.", "Check bear-related closures and park access arrangements. Carry bear spray and know how to use it.", "June–September", "glacier", "Trail of the Cedars"],
  ["hidden-lake-overlook", "Hidden Lake Overlook", "Glacier National Park", "Rockies", 4.4, 140, "1.5–2.5 hr", "Moderate", "Out & Back", "glacier", ["Alpine", "Lake", "Wildlife"], "Open alpine country and a lake tucked beneath sculpted peaks.", "Follow the boardwalk and trail behind Logan Pass Visitor Center to the overlook; return without descending to the lake.", "Check snow and wildlife closures. Keep distance from mountain goats and stay on the trail.", "July–September, snow permitting", "glacier", "Logan Pass Visitor Center"],
  ["fairy-falls", "Fairy Falls", "Yellowstone National Park", "Rockies", 8.6, null, "3–4 hr", "Easy", "Out & Back", "fairy", ["Waterfalls", "Forest"], "A quiet forest approach ends at a slender ribbon of falling water.", "Use the southern Fairy Falls approach for the shorter of the park’s described itineraries; return by the same path.", "Confirm the open approach and seasonal bear restrictions. Stay on trails around thermal areas.", "Summer–fall", "fairy", "Fairy Falls southern trailhead"],
  ["taggart-lake", "Taggart Lake", "Grand Teton National Park", "Rockies", 4.8, 110, "2 hr", "Easy", "Out & Back", "taggart", ["Lake", "Peaks", "Forest"], "A lakeside pause beneath the sharp profile of the Tetons.", "Follow the Taggart Lake trail to the lake and back.", "Check trailhead construction and access before travel. Give wildlife space.", "June–October", "taggart", "Taggart Lake trailhead"],
  ["hidden-falls-jenny-lake", "Hidden Falls via Jenny Lake", "Grand Teton National Park", "Rockies", 8, null, "3–4 hr", "Moderate", "Out & Back", "hidden-falls-jenny-lake", ["Lake", "Waterfalls", "Forest"], "Pair the lakeshore with a waterfall at the foot of the Tetons.", "Walk from the Jenny Lake visitor area around the southern lakeshore to Hidden Falls and return on foot.", "Distance excludes the optional boat shuttle. Check wildlife closures and allow time for the return.", "June–September", "jenny", "Jenny Lake Visitor Center"],
  ["diamond-head", "Diamond Head Summit", "Oʻahu", "Hawaii", 2.6, 171, "1.5–2 hr", "Strenuous", "Out & Back", "diamond-head", ["Coast", "Volcanic", "Views"], "See Honolulu and the Pacific from inside an iconic volcanic landmark.", "Climb from the crater floor via switchbacks, stairs and a tunnel to the summit; return.", "Non-residents need entry and parking reservations. Bring water; the final stairs are steep.", "Year-round; cooler morning hours", "diamond", "Diamond Head crater parking area"],
  ["kilauea-iki", "Kīlauea Iki", "Hawaiʻi Volcanoes National Park", "Hawaii", 5.3, 122, "2–3 hr", "Moderate", "Loop", "kilauea", ["Volcanic", "Rainforest", "Geology"], "From rainforest shade to the floor of a solidified lava lake.", "Descend from Kīlauea Iki Overlook, cross the crater on the marked trail and climb back to the rim.", "Check volcanic activity and air-quality alerts. The crater is exposed; carry rain and sun protection.", "Year-round, conditions permitting", "kilauea", "Kīlauea Iki Overlook"],
  ["devastation-trail", "Devastation Trail", "Hawaiʻi Volcanoes National Park", "Hawaii", 1.6, null, "1 hr", "Easy", "Out & Back", "devastation", ["Volcanic", "Nature", "Geology"], "Watch a forest return to a landscape reshaped by eruption.", "Follow the paved trail through the cinder landscape and return to your starting parking area.", "Stay on paving and do not feed nēnē. Check volcanic alerts before visiting.", "Year-round, conditions permitting", "devastation", "Devastation Trail parking area"],
];

export const trails: Trail[] = seeds.map(([slug, name, destination, region, distanceKm, elevationGainM, duration, difficulty, routeType, imageKey, tags, whyGo, route, guidance, bestTime, source, trailhead]) => ({
  slug, name, destination, region, country: "United States", distanceKm, elevationGainM, duration, difficulty, routeType, imageKey, tags, whyGo, route, guidance, bestTime,
  sourceUrl: sources[source], reviewedAt: "2026-09-09", map: { trailhead: { name: trailhead }, waypoints: [] },
}));

export function findTrail(slug: string) { return trails.find(trail => trail.slug === slug); }
export function filterTrails(query: string, difficulty = "All", region = "All") {
  const terms = query.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().split(/\s+/).filter(Boolean);
  return trails.filter(trail => {
    const text = [trail.name, trail.destination, trail.region, ...trail.tags].join(" ").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    return (difficulty === "All" || trail.difficulty === difficulty) && (region === "All" || trail.region === region) && terms.every(term => text.includes(term));
  });
}



