export type SnowKind = "Resort" | "Ski region";
export interface SnowDestination { slug: string; name: string; location: string; region: string; kind: SnowKind; terrain: string; season: string; summary: string; sourceUrl: string }
export const snowDestinations: SnowDestination[] = [
  ["whistler-blackcomb","Whistler Blackcomb","British Columbia, Canada","Canada","Resort","Two linked mountains with a broad mix of alpine and tree skiing.","Northern winter","A big-mountain base for long ski days and a village-built trip.","https://www.whistlerblackcomb.com/"],
  ["banff-sunshine","Banff Sunshine","Alberta, Canada","Canada","Resort","High alpine bowls and open terrain in Banff National Park.","November–May","A high-elevation ski day surrounded by the Canadian Rockies.","https://www.skibanff.com/"],
  ["lake-louise","Lake Louise Ski Resort","Alberta, Canada","Canada","Resort","Front-side groomers, bowls and mountain views above Lake Louise.","November–May","A classic Rockies resort that works well inside a wider Banff trip.","https://www.skilouise.com/"],
  ["revelstoke","Revelstoke Mountain Resort","British Columbia, Canada","Canada","Resort","Long vertical, glades and advanced alpine terrain.","December–April","For skiers and riders who want the mountain to be the main event.","https://www.revelstokemountainresort.com/"],
  ["park-city","Park City Mountain","Utah, United States","United States","Resort","A large linked trail network with direct town access.","November–April","Easy logistics, varied terrain and a historic mountain-town base.","https://www.parkcitymountain.com/"],
  ["jackson-hole","Jackson Hole Mountain Resort","Wyoming, United States","United States","Resort","Steep alpine terrain, bowls and substantial vertical.","November–April","A serious mountain with a strong sense of place in the Tetons.","https://www.jacksonhole.com/"],
  ["aspen-snowmass","Aspen Snowmass","Colorado, United States","United States","Ski region","Four mountains connected by one destination base.","November–April","Choose a mountain to match the day, from mellow cruising to steep lines.","https://www.aspensnowmass.com/"],
  ["chamonix","Chamonix Mont-Blanc","France","Europe","Ski region","Multiple mountain areas beneath the Mont Blanc massif.","December–April","An alpine town for experienced skiers who plan carefully and use local guidance.","https://www.chamonix.com/"],
  ["zermatt","Zermatt","Switzerland","Europe","Ski region","High-altitude skiing beneath the Matterhorn with linked terrain toward Italy.","November–April","A car-free alpine trip where the journey and the mountain belong together.","https://www.zermatt.ch/en"],
  ["niseko-united","Niseko United","Hokkaido, Japan","Japan","Ski region","Four connected areas known for frequent winter snow and tree skiing.","December–April","A Hokkaido snow trip with several bases and a strong food culture beyond the lifts.","https://www.niseko.ne.jp/en/"],
  ["coronet-peak","Coronet Peak","Queenstown, New Zealand","New Zealand","Resort","Open groomed terrain close to Queenstown.","June–October","A Southern Hemisphere ski day that fits naturally into a Queenstown trip.","https://www.coronetpeak.co.nz/"],
  ["falls-creek","Falls Creek","Victoria, Australia","Australia","Resort","A pedestrian alpine village with groomed runs and Nordic access.","June–October","An Australian winter base with village convenience and varied snow activities.","https://www.fallscreek.com.au/"],
].map(([slug,name,location,region,kind,terrain,season,summary,sourceUrl]) => ({slug,name,location,region,kind: kind as SnowKind,terrain,season,summary,sourceUrl}));
export function findSnow(slug: string) { return snowDestinations.find(item => item.slug === slug); }
export function filterSnow(query = "", region = "All", kind = "All") { const q=query.trim().toLowerCase(); return snowDestinations.filter(item => (!q || `${item.name} ${item.location} ${item.terrain}`.toLowerCase().includes(q)) && (region === "All" || item.region === region) && (kind === "All" || item.kind === kind)); }
