import type {Metadata} from "next";import {notFound} from "next/navigation";import Link from "next/link";
import {CharacterMeter} from "@/green/components/character-meter";import {CourseMap} from "@/green/components/course-map";import {CourseMode} from "@/green/components/course-mode";import {CourseVisual} from "@/green/components/course-visual";import {LibraryActions} from "@/green/components/library-actions";import {RelatedCourses} from "@/green/components/related-courses";
import {publishedCollections} from "@/green/data/collections";import {getCourse,publishedCourses} from "@/green/data/courses";import {getDestination} from "@/green/data/destinations";import {getCourseMedia} from "@/green/data/media";import{getTripsForCourse}from"@/green/data/trips";
type Props={params:Promise<{slug:string}>};export function generateStaticParams(){return publishedCourses.map(course=>({slug:course.slug}))}export async function generateMetadata({params}:Props):Promise<Metadata>{const course=getCourse((await params).slug);return course?{title:course.name,description:course.editorial.shortDescription}:{}}
export default async function CoursePage({params}:Props){const course=getCourse((await params).slug);if(!course)notFound();const destination=course.destinationSlug?getDestination(course.destinationSlug):undefined;const media=getCourseMedia(course.slug);const courseCollections=publishedCollections.filter(c=>c.courseSlugs.includes(course.slug));const trips=getTripsForCourse(course.slug);return <main>
<div className="course-appbar"><div className="shell"><Link href="/green/">← Discover</Link><span>{course.shortName??course.name}</span><a href="#course-mode">Course Mode</a></div></div>
<header className="course-hero shell"><CourseVisual course={course} hero/><div><p className="eyebrow">{destination?<Link href={`/green/destinations/${destination.slug}`}>{destination.name}</Link>:course.location.region} · {course.location.country}</p><h1>{course.name}</h1><p className="headline">{course.editorial.headline}</p><div className="essential-meta"><span>{course.holes} holes</span><span>Par {course.par}</span><span>{course.yards.toLocaleString()} yards</span><span>{course.access.type}</span></div><LibraryActions slug={course.slug}/></div></header>
<nav className="section-nav" aria-label="Course sections"><a href="#why">Why play</a><a href="#character">Character</a><a href="#journey">Journey</a><a href="#holes">Holes</a><a href="#know">Know before</a></nav>
<article className="course-content shell"><section id="why" className="prose-lead"><p className="eyebrow">Why play it</p><h2>{course.editorial.whyPlay}</h2><p>{course.editorial.story}</p></section>
<section id="character"><div className="section-heading"><div><p className="eyebrow">Course character</p><h2>A concise read of the experience.</h2></div><span>Editorial, not scientific</span></div><CharacterMeter course={course}/></section>
<section className="glance"><p className="eyebrow">At a glance</p><dl><div><dt>Architect</dt><dd>{course.architect}</dd></div><div><dt>Opened</dt><dd>{course.openingYear}</dd></div><div><dt>Access</dt><dd>{course.access.publicAccess}</dd></div><div><dt>Typical round</dt><dd>{course.typicalRoundDuration}</dd></div><div><dt>Season</dt><dd>{course.season}</dd></div><div><dt>Approximate fee</dt><dd>{course.greenFee.display}<small>{course.greenFee.note}</small></dd></div></dl></section>
<section id="journey"><p className="eyebrow">Course Journey</p><h2>The shape of the round.</h2><div className="journey-list">{course.journey.map((chapter,index)=><article key={chapter.range}><b>{String(index+1).padStart(2,"0")}</b><div><span>{chapter.range}</span><h3>{chapter.title}</h3><p>{chapter.description}</p></div></article>)}</div></section>
<section id="holes"><p className="eyebrow">Signature holes</p><h2>Moments that explain the course.</h2><div className="hole-grid">{course.signatureHoles.map(hole=><article key={hole.number}><p className="eyebrow">{hole.label??"Course moment"}</p><span>Hole {hole.number}</span><h3>{hole.name??`Par ${hole.par}`}</h3><small>Par {hole.par} · {hole.yards} yards</small><p>{hole.description}</p>{hole.strategy?<aside><b>Strategy</b>{hole.strategy}</aside>:null}</article>)}</div></section>
<section id="know" className="know-grid"><div><p className="eyebrow">Know before you go</p><h2>Arrive with context.</h2><ul>{course.editorial.knowBeforeYouGo.map(item=><li key={item}>{item}</li>)}</ul><h3>Amenities</h3><p>{course.amenities.join(" · ")}</p><div className="profile-actions">{course.bookingUrl?<a className="primary-button" href={course.bookingUrl} target="_blank" rel="noreferrer">Visit official course ↗</a>:null}<Link className="primary-button" href={`/green/plan?course=${course.slug}`}>Plan around this course →</Link></div><small>External operational source · Last editorial check {course.greenFee.lastVerified}</small></div><CourseMap courses={[course]} height="small"/></section>
<section id="course-mode"><CourseMode course={course}/></section>{(courseCollections.length||trips.length)?<section className="profile-collections"><p className="eyebrow">Continue the journey</p><div>{trips.map(t=><Link href={`/green/trips/${t.slug}`} key={t.slug}>Trip · {t.title} →</Link>)}{courseCollections.map(c=><Link href={`/green/collections/${c.slug}`} key={c.slug}>Collection · {c.title} →</Link>)}</div></section>:null}<RelatedCourses slug={course.slug}/>
<section className="sources"><p className="eyebrow">Sources & integrity</p><h2>Operational facts remain changeable.</h2>{media?<p><a href={media.sourceUrl} target="_blank" rel="noreferrer">Photography: {media.creator} · {media.license} ↗</a><br/><small>{media.reuseNotes}</small></p>:<p><small>Documentary photography is pending a verified reuse license.</small></p>}{course.sources.map(source=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a> · checked {source.lastVerified}<br/><small>{source.note}</small></p>)}</section></article></main>}
