import Link from "next/link";
import { RouteCard } from "@/components/route-card";
import { SiteHeader } from "@/components/site-header";
import { getAllRoutes } from "@/data/routes";
import { featuredRouteSlugs } from "@/data/featured-routes";

export default function HomePage() {
  const routes = getAllRoutes();
  const featuredRoutes = featuredRouteSlugs.map((slug) => routes.find((route) => route.summary.slug === slug)).filter((route) => route !== undefined);
  return <><SiteHeader /><main>
    <section className="site-shell flex min-h-[62vh] items-center py-20 sm:py-28"><div className="max-w-4xl"><p className="eyebrow">Curated rail journeys</p><h1 className="mt-5 font-serif text-6xl leading-[0.95] tracking-tight sm:text-8xl lg:text-9xl">Rallii</h1><p className="mt-7 max-w-3xl font-serif text-3xl leading-tight text-stone-700 sm:text-5xl">Know where to sit, what to see, and when to look.</p><p className="mt-7 max-w-xl text-base leading-7 text-stone-600 sm:text-lg">Extraordinary railway journeys, curated around the experience outside your window.</p><div className="mt-9 flex flex-wrap gap-5"><Link className="cta-button focus-ring" href="/discover">Explore journeys</Link><Link className="secondary-link focus-ring" href="/search">Search Rallii <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="border-t border-stone-300 py-16 sm:py-24" id="featured" aria-labelledby="featured-title"><div className="site-shell"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Curated for Rallii</p><h2 id="featured-title" className="mt-2 font-serif text-4xl sm:text-5xl">Featured Journeys</h2></div><Link className="primary-link focus-ring" href="/discover">View all journeys <span aria-hidden="true">→</span></Link></div><div className="mt-9 grid gap-7 lg:grid-cols-3">{featuredRoutes.map((route) => <RouteCard key={route.summary.slug} route={route} />)}</div></div></section>
    <section className="border-t border-stone-300 py-16 sm:py-24" aria-labelledby="explore-title"><div className="site-shell"><p className="eyebrow">A growing collection</p><h2 id="explore-title" className="mt-2 font-serif text-4xl sm:text-5xl">Explore by Journey</h2><div className="mt-8 grid gap-px bg-stone-300 sm:grid-cols-3">{[ ["Across the Alps","High passes, deep valleys, and journeys shaped by mountain landscapes."], ["Panoramic Trains","Services designed to bring the landscape closer to your seat."], ["UNESCO Railways","Railways recognised for the way engineering and landscape meet."] ].map(([title,copy]) => <div className="bg-page p-6 sm:p-8" key={title}><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{copy}</p></div>)}</div></div></section>
    <section className="border-t border-stone-300 py-16 sm:py-24" aria-labelledby="why-title"><div className="site-shell"><p className="eyebrow">Why Rallii</p><h2 id="why-title" className="mt-2 max-w-2xl font-serif text-4xl sm:text-5xl">See more from the journey.</h2><div className="mt-10 grid gap-8 sm:grid-cols-3">{[["Know where to sit","Directional seat-view guidance that changes with the journey."],["Know what’s coming","Scenic landmarks arranged in the order you’ll meet them."],["Know when to look","A calm timeline for the moments worth your attention."]].map(([title,copy],i) => <div className="border-t border-stone-300 pt-5" key={title}><span className="text-xs text-stone-500">0{i+1}</span><h3 className="mt-3 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{copy}</p></div>)}</div></div></section>
  </main></>;
}
