"use client";
import { useState } from "react";
import { RouteCard } from "@/components/route-card";
import type { RailRoute } from "@/types/route";
const filters = ["all", "switzerland", "italy", "ireland", "northern-ireland", "united-kingdom", "norway", "new-zealand", "japan", "cross-border"] as const;
export type DiscoverFilter = (typeof filters)[number];
export function isDiscoverFilter(value: string | undefined): value is DiscoverFilter { return filters.includes(value as DiscoverFilter); }
export function filterRoutes(routes: RailRoute[], filter: DiscoverFilter): RailRoute[] { if (filter === "all") return routes; if (filter === "cross-border") return routes.filter((route) => route.summary.journeyTypes.includes("cross-border")); if (filter === "northern-ireland") return routes.filter((route) => route.summary.slug === "belfast-derry"); const country = filter === "united-kingdom" ? "United Kingdom" : filter === "new-zealand" ? "New Zealand" : filter.charAt(0).toUpperCase() + filter.slice(1); return routes.filter((route) => route.summary.countries.includes(country)); }
export function DiscoverRoutes({ routes, initialFilter = "all" }: { routes: RailRoute[]; initialFilter?: DiscoverFilter }) { const [filter, setFilter] = useState<DiscoverFilter>(initialFilter); const visible = filterRoutes(routes, filter); return <><div className="mt-8 flex gap-2 overflow-x-auto pb-2" aria-label="Filter journeys">{filters.map((item) => <button className={`filter-button shrink-0${filter === item ? " filter-button--active" : ""}`} key={item} type="button" aria-pressed={filter === item} onClick={() => setFilter(item)}>{item === "all" ? "All" : item.split("-").map((part) => part.charAt(0).toUpperCase()+part.slice(1)).join(" ")}</button>)}</div><div className="mt-8 grid gap-7 lg:grid-cols-2">{visible.map((route) => <RouteCard key={route.summary.slug} route={route} />)}</div></>; }
