import Link from "next/link";
import { RouteMedia } from "@/components/route-media";
import { getCollectionCover, getCollectionRoutes, journeyCollections, promotedCollectionSlugs } from "@/data/journey-collections";
import type { RailRoute } from "@/types/route";

export function JourneyCollections({ routes, limit, compact = false }: { routes: RailRoute[]; limit?: number; compact?: boolean }) {
  const promoted = promotedCollectionSlugs.map((slug) => journeyCollections.find((collection) => collection.slug === slug)).filter((collection) => collection !== undefined);
  const collections = (compact ? promoted : journeyCollections).slice(0, limit);
  if (compact) return <section className="catalogue-collections" aria-labelledby="collections-title"><div className="discover-filter-heading"><p id="collections-title">Curated collections</p><Link className="text-link focus-ring" href="/discover/collections">View all</Link></div><div className="catalogue-collection-grid">{collections.map((collection) => { const members = getCollectionRoutes(collection, routes); const cover = getCollectionCover(collection, routes); return <article className="catalogue-collection-card" key={collection.slug}>{cover ? <RouteMedia summary={cover.summary} variant="card" /> : null}<div><strong>{collection.title}</strong><span>{members.length} journeys</span><Link className="focus-ring" href={`/discover/${collection.slug}`} aria-label={`Explore ${collection.title}`}>Explore <span aria-hidden="true">→</span></Link></div></article>; })}</div></section>;
  return <section className="section-space border-t border-stone-300 pt-14 sm:pt-20" aria-labelledby="collections-title"><div className="section-heading"><div><p className="eyebrow">Explore by experience</p><h2 id="collections-title" className="mt-2 font-serif text-4xl sm:text-5xl">What kind of journey?</h2></div><Link className="secondary-link focus-ring" href="/discover">Browse Discover →</Link></div><div className="mt-9 grid gap-5 lg:grid-cols-2">{collections.map((collection) => { const members = getCollectionRoutes(collection, routes); return <article className="collection-card" key={collection.slug}><div><h3 className="font-serif text-3xl">{collection.title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{collection.description}</p><p className="mt-5 text-xs font-bold uppercase tracking-wider text-stone-500">{members.map((route) => route.summary.name).join(" · ")}</p><Link className="primary-link mt-5" href={`/discover/${collection.slug}`}>Explore {collection.title} <span aria-hidden="true">→</span></Link></div><div className="collection-media" aria-hidden="true">{members.slice(0, 2).map((route) => <RouteMedia key={route.summary.slug} summary={route.summary} variant="card" />)}</div></article>; })}</div></section>;
}
