"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { RideMap } from "@/components/ride-map";
import { formatAheadDistance, formatRideSide, getMatchConfidence, getNextHighlight, getPreviousHighlight, getRideSide } from "@/lib/ride-guidance";
import { interpolateRouteCoordinate, projectCoordinateOntoRoute, routeLengthKm, type RouteCoordinate } from "@/lib/route-geometry";
import type { RailRoute } from "@/types/route";

type Mode = "landing" | "location" | "demo";
interface RouteGeoJson { features: Array<{ geometry: { coordinates: RouteCoordinate[] } }> }

export function RideMode({ route }: { route: RailRoute }) {
  const [geometry, setGeometry] = useState<RouteCoordinate[]>(); const [mode, setMode] = useState<Mode>("landing"); const [progress, setProgress] = useState(0); const [position, setPosition] = useState<RouteCoordinate>(); const [distanceFromRoute, setDistanceFromRoute] = useState(0); const [status, setStatus] = useState(""); const watchId = useRef<number | undefined>(undefined);
  useEffect(() => { fetch(route.geoJsonPath).then((response) => response.json()).then((data: RouteGeoJson) => setGeometry(data.features[0]?.geometry.coordinates)).catch(() => setStatus("The prepared route could not be loaded.")); }, [route.geoJsonPath]);
  const stopWatching = useCallback(() => { if (watchId.current !== undefined) navigator.geolocation.clearWatch(watchId.current); watchId.current = undefined; }, []);
  useEffect(() => stopWatching, [stopWatching]);
  function startDemo() { stopWatching(); if (!geometry) { setStatus("The prepared route is still loading."); return; } setMode("demo"); setStatus("Demo Mode uses simulated progress along the prepared railway route."); setProgress(0); setPosition(interpolateRouteCoordinate(geometry, 0)); setDistanceFromRoute(0); }
  function updateDemo(value: number) { if (!geometry) return; setProgress(value); setPosition(interpolateRouteCoordinate(geometry, value)); }
  function useLocation() { if (!geometry) { setStatus("The prepared route is still loading."); return; } if (!("geolocation" in navigator)) { setStatus("Location is not supported by this browser. Try Demo Mode instead."); return; } stopWatching(); setMode("location"); setStatus("Waiting for your location…"); watchId.current = navigator.geolocation.watchPosition(({ coords }) => { const projection = projectCoordinateOntoRoute([coords.longitude, coords.latitude], geometry); setPosition(projection.nearestCoordinate); setDistanceFromRoute(projection.distanceFromRouteMeters); setProgress(projection.progress); const confidence = getMatchConfidence(projection.distanceFromRouteMeters); setStatus(confidence === "on-route" ? "You’re matched to the Flåm Railway." : confidence === "near-route" ? "You appear to be near the Flåm Railway; progress is approximate." : "You don’t appear to be near the Flåm Railway."); }, (error) => { setMode("landing"); setStatus(error.code === error.PERMISSION_DENIED ? "Location access is off. Try Demo Mode or enable location and try again." : error.code === error.TIMEOUT ? "Location timed out. Try again or use Demo Mode." : "We couldn’t determine your location. Try again or use Demo Mode."); }, { enableHighAccuracy: true, timeout: 12_000, maximumAge: 5_000 }); }
  function endRide() { stopWatching(); setMode("landing"); setPosition(undefined); setProgress(0); setStatus(""); }
  const totalKm = geometry ? routeLengthKm(geometry) : route.summary.distanceKm; const distanceKm = Math.min(totalKm, totalKm * progress); const upcoming = getNextHighlight(route, distanceKm); const previous = getPreviousHighlight(route, distanceKm); const landmark = upcoming?.relatedLandmarkId ? route.landmarks.find((item) => item.id === upcoming.relatedLandmarkId) : undefined; const arrived = progress >= 0.995; const side = getRideSide(route, distanceKm, upcoming); const ahead = upcoming ? Math.max(0, upcoming.distanceAlongRouteKm - distanceKm) : 0;
  if (mode === "landing") return <section className="ride-landing"><p className="eyebrow">Ride Mode</p><h2 className="mt-2 font-serif text-4xl">Follow your progress</h2><p className="mt-4 max-w-xl leading-7 text-stone-600">See what’s coming as Rallii compares your device’s location with the prepared Flåm Railway route.</p><ul className="ride-privacy"><li>Your location stays in this browser.</li><li>No account is required.</li><li>Rallii does not store or transmit your coordinates.</li></ul><div className="mt-7 flex flex-wrap gap-3"><button className="cta-button" type="button" onClick={useLocation}>Use My Location</button><button className="action-button" type="button" onClick={startDemo}>Try Demo Mode</button></div><p className="mt-5 text-sm text-stone-600" role="status" aria-live="polite">{status}</p></section>;
  return <div className="ride-active"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{mode === "demo" ? "Demo Mode" : "Ride Mode"}</p><h2 className="mt-2 font-serif text-4xl">You’re on the Flåm Railway</h2></div><button className="action-button" type="button" onClick={endRide}>End Ride Mode</button></div><p className="mt-4 text-sm text-stone-600" role="status" aria-live="polite">{status}</p>{position ? <RideMap geoJsonPath={route.geoJsonPath} endpoints={[route.stops[0], route.stops.at(-1)!]} position={position} upcoming={landmark} /> : null}<section className="ride-progress" aria-labelledby="progress-title"><p className="eyebrow">Your journey</p><h3 id="progress-title" className="sr-only">Journey progress</h3><div className="ride-progress-labels"><span>{route.summary.origin}</span><span>{route.summary.destination}</span></div><div className="ride-progress-track"><span style={{ width: `${progress * 100}%` }} /></div><p><strong>About {distanceKm.toFixed(1)} km of {totalKm.toFixed(1)} km</strong> · {Math.round(progress * 100)}% of the journey</p>{mode === "location" && distanceFromRoute > 150 ? <p className="mt-2 text-xs text-stone-500">Position match is approximate.</p> : null}</section>{arrived ? <section className="ride-up-next ride-up-next--now"><p className="eyebrow">Myrdal</p><h3 className="mt-2 font-serif text-4xl">You’ve reached the end of the journey.</h3><Link className="primary-link mt-6" href={`/routes/${route.summary.slug}`}>View Flåm Railway →</Link></section> : upcoming ? <section className={`ride-up-next${ahead <= 0.3 ? " ride-up-next--now" : ""}`}><p className="eyebrow">{ahead <= 0.3 ? "Look now" : ahead <= 1 ? "Coming up" : "Up next"}</p><h3 className="mt-2 font-serif text-4xl">{upcoming.subtitle ?? upcoming.title}</h3><p className="mt-3 text-sm font-semibold text-stone-600">{formatAheadDistance(ahead)}</p><p className="mt-4 max-w-xl text-sm leading-6 text-stone-600">{upcoming.shortDescription}</p><p className="mt-5 text-xl font-semibold text-accent">{formatRideSide(side)}</p></section> : null}{previous && !arrived ? <p className="ride-previous"><span>Previously</span>{previous.subtitle ?? previous.title}</p> : null}{mode === "demo" ? <section className="ride-demo-control"><label htmlFor="demo-progress">Demo progress <strong>{Math.round(progress * 100)}%</strong></label><input id="demo-progress" type="range" min="0" max="100" value={Math.round(progress * 100)} onChange={(event) => updateDemo(Number(event.target.value) / 100)} /><div><span>Flåm</span><span>Myrdal</span></div><div className="ride-demo-steps" aria-label="Demo progress shortcuts">{[0, 25, 50, 75, 100].map((value) => <button type="button" key={value} aria-label={`Set demo progress to ${value}%`} aria-pressed={Math.round(progress * 100) === value} onClick={() => updateDemo(value / 100)}>{value}%</button>)}</div></section> : null}</div>;
}
