import type { Metadata } from "next";
import Link from "next/link";
import { AppScreenShell } from "@/components/app-screen-shell";

export const metadata: Metadata = { title: "Terms of Use", description: "Terms for using Rallii’s editorial rail-journey guides." };

export default function TermsPage() {
  return <AppScreenShell title="Terms of Use" context="Effective 16 August 2026" backHref="/" backLabel="Home"><article className="legal-copy"><p>Rallii provides curated editorial information about rail journeys. It is not a railway operator, travel agent, booking service, timetable authority, or real-time journey planner.</p><h2>Check before travel</h2><p>Routes, schedules, connections, reservations, accessibility, weather, operating conditions, and onboard services can change. Confirm current information directly with the relevant operator before travelling.</p><h2>Maps and guidance</h2><p>Prepared geometry, scenic timelines, landmarks, and Best Side guidance are informational and may be approximate. They must not be used for safety-critical navigation.</p><h2>External services</h2><p>Partner searches and external links are provided for convenience. Any reservation or purchase is made directly with the external provider under that provider’s terms. Rallii may receive an affiliate commission but does not guarantee partner availability, pricing, or service.</p><h2>Acceptable use</h2><p>Do not misuse, disrupt, scrape at unreasonable volume, or attempt to interfere with Rallii or its providers. Photography, editorial content, and third-party data remain subject to their stated rights and licences.</p><h2>Service availability</h2><p>Rallii may change or withdraw features and content. These terms do not represent app-store approval or guarantee future native availability.</p><p><Link href="/privacy">Read the Privacy Policy</Link> · <a href="https://jordypop.vercel.app/work/rallii" target="_blank" rel="noreferrer">Rallii family</a></p></article></AppScreenShell>;
}
