import type { Metadata } from "next";
import Link from "next/link";
import { AppScreenShell } from "@/components/app-screen-shell";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Rallii handles local preferences and external partner searches." };

export default function PrivacyPage() {
  return <AppScreenShell title="Privacy Policy" context="Effective 28 August 2026" backHref="/" backLabel="Home"><article className="legal-copy"><p>Rallii is an editorial rail-journey discovery service. You can browse its prepared guides without creating an account.</p><h2>Information stored on your device</h2><p>Saved journey preferences and similar personal-library choices are stored locally in your browser. Rallii does not use this information to create a user profile on its servers.</p><h2>Infrastructure</h2><p>Basic technical request information may be processed by Rallii’s hosting and infrastructure providers to deliver and protect the service.</p><h2>External partners and affiliate links</h2><p>Plan and Stays may load tools from Agoda, Trip.com, DiscoverCars, GetYourGuide, Stay22, or Travelpayouts after you choose to open them. Those companies operate their own websites and widgets and may collect information under their own privacy policies. Rallii may earn a commission from qualifying partner activity at no additional cost to you.</p><p>Rallii does not process bookings, payments, prices, or availability. Review the partner’s terms and privacy information before continuing.</p><h2>Your choices</h2><p>You may clear locally saved Rallii information through your browser settings. Blocking third-party content may prevent partner tools from loading without affecting the editorial route guides.</p><h2>Contact and changes</h2><p>This policy will be updated as Rallii’s service and distribution change. For privacy questions or support, use the maintained contact options on the Rallii project page.</p><p><Link href="/terms">Read the Terms of Use</Link> · <a href="https://jordypop.vercel.app/work/rallii" target="_blank" rel="noreferrer">Rallii project page</a></p></article></AppScreenShell>;
}
